#!/usr/bin/env ruby

require 'runeblog'

lib = RuneBlog::Path

files = Dir["lib/*.rb"]
bad = false
files.each do |f|
  msg = `ruby -c #{f} 2>&1`
  if msg !~ /Syntax OK/
    bad = true
    err = msg.split("\n")[0]
    puts "#{err}   (Press return to edit)"
    STDIN.gets
    file, line, * = err.split(":")
    system("vi #{file} +#{line}")
  end
end

abort "\nYou'll need to re-run\n " if bad


# Let's go!

system("livetext -i lib/liveblog.rb")

system("cp lib/* #{lib}/")

puts "tar operation..."
rc = system("tar zcvf empty_view.tgz empty_view 2>/dev/null")
puts "Error 1!" unless rc

rc = system("cp empty_view.tgz #{lib}/..")
puts "Error 2!" unless rc

puts "...finished"

# Exception in dir structure
cmd = "cp bin/* #{lib.sub(/lib$/, "bin/")}"
puts cmd
system(cmd)

# puts

